### ISSUE TITLE
a code for speech recognition in python

### ISSUE THREAD

**Issue by ameraibrahiem** [Pixdigit/Project-Interstellar#29]
Traceback (most recent call last):
  File "C:/Python27/okay.py", line 15, in <module>
    with sr.Microphone(device_index = device_id, sample_rate = sample_rate,
NameError: name 'device_id' is not defined

i don't know how to fix this error in the code

**Comment by Pixdigit** [comment]
Hello there. I think you got the wrong project. This is project Interstellar. A game not a speech recognition  software.
